# Generated by Django 4.2.30 on 2026-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_variant_variantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
