# Generated by Django 4.2.30 on 2026-07-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_categoryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryimage',
            options={'ordering': ['-is_primary', 'created_at'], 'verbose_name': 'Category Image', 'verbose_name_plural': 'Category Images'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
