# Generated by Django 4.2.30 on 2026-07-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_categoryimage_options_remove_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
