# Generated by Django 4.2.30 on 2026-08-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_image_delete_categoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
