# Generated by Django 4.2.30 on 2026-08-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='total_amount',
        ),
    ]
