# Generated by Django 4.2.30 on 2026-08-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_rename_tax_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected')], default='PENDING', max_length=25),
        ),
    ]
