# Generated by Django 4.2.30 on 2026-08-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_offer', '0001_initial'),
        ('Order', '0004_orderitem_rejection_reason_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupon_offer.coupon'),
        ),
    ]
