# Generated by Django 4.2.30 on 2026-09-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('WALLET', 'Wallet')], default='COD', max_length=20),
        ),
    ]
