# Generated by Django 4.2.30 on 2026-09-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_order_address_city_order_address_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
